version: "3.7"

services:
  course-app:
    container_name: course-app
    build:
      context: .
    ports:
      - "3000:3000"
    command: npm run start:dev
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app

  course-database:
    container_name: course-database
    image: mysql:8.0.32
    volumes:
      - course-database-volume:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"

volumes:
  course-database-volume: